# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MobileInspectionApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   

  # Pods for MobileInspectionApp
   pod 'Firebase'
   pod 'Firebase/Analytics'
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'Firebase/Messaging'

  target 'MobileInspectionAppTests' do
    inherit! :search_paths
   
    # Pods for testing
  end

end
